dommel_travel_diary_api_user_login:
    path:     /user/login
    defaults: { _controller: DommelTravelDiaryApiBundle:User:login }
    methods:  [ POST ]

dommel_travel_diary_api_user_current:
    path:     /user/current
    defaults:
        _controller: DommelTravelDiaryApiBundle:User:current
    methods:  [ GET ]

dommel_travel_diary_api_user_logout:
    path:      /user/logout
    defaults:
        _controller: DommelTravelDiaryApiBundle:User:logout
    methods: [ POST ]

dommel_travel_diary_api_diary_get:
    path:     /diary/{id}
    defaults:
        _controller: DommelTravelDiaryApiBundle:Diary:getDiary
    methods: [ GET ]

dommel_travel_diary_api_diary_create:
    path:     /diary/create
    defaults:
        _controller: DommelTravelDiaryApiBundle:Diary:create
    methods: [ POST ]

dommel_travel_diary_api_diary_all:
    path: /diaries
    defaults:
        _controller: DommelTravelDiaryApiBundle:Diary:getDiaries
    methods: [ GET ]

dommel_travel_diary_api_diary_photo_add:
    path: /diary/{diaryId}/photo
    defaults:
        _controller: DommelTravelDiaryApiBundle:Diary:addPhoto
    methods: [ POST ]