parameters:
#    dommel_travel_diary_api.example.class: Dommel\TravelDiary\ApiBundle\Example

services:
    login_service:
        class: Dommel\TravelDiary\ApiBundle\Services\User\LoginService
        arguments: [ @doctrine.orm.entity_manager, @security_service]

    register_service:
        class: Dommel\TravelDiary\ApiBundle\Services\User\RegisterService
        arguments: [ @doctrine.orm.entity_manager, @security_service ]

    security_service:
        class: Dommel\TravelDiary\ApiBundle\Services\Security\SecurityService
        arguments: [  ]

    session_service:
        class: Dommel\TravelDiary\ApiBundle\Services\Session\SessionService
        arguments: [ @doctrine.orm.entity_manager ]

    diary_service:
        class: Dommel\TravelDiary\ApiBundle\Services\Diary\DiaryService
        arguments: [ @doctrine.orm.entity_manager ]