dommel_travel_diary_login:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DommelTravelDiaryWebBundle:Public:login.html.twig'
        private: false

dommel_travel_diary_start:
    pattern: /start
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'DommelTravelDiaryWebBundle:Public:start.html.twig'
        private: false